-- Seed Participating Congregations
INSERT INTO congregation (name, description, mission, banner_photo_directory) VALUES
('Cross of Christ', 'Located in Bountiful, Utah.', 'Cross of Christ is men, women and children who know Christ and desire to make Christ known.', 'cross-of-christ-bountiful'),
('Redeemer', 'Located in Salt Lake City, Utah.', 'Reaching people for Jesus Christ, embracing them in a Christ-centered community, and nurturing them in God''s Word to be faithful disciples.', 'redeemer-slc'),
('St. John', 'Located in Salt Lake City, Utah. An eighty-plus-year-old Lutheran Church.', 'To share the Good News of the gift of complete forgiveness of all sins and guilt through Jesus in the Word and Sacrament ministry.', 'st-john-slc'),
('Grace (Sandy)', 'Located in Sandy, Utah.', 'Proclaiming the Gospel of Christ, Nurturing Faith, Reaching out with the love of Christ, and Providing Christian Fellowship.', 'grace-sandy'),
('Grace (Spanish Fork)', 'A satellite congregation of Grace in Sandy, located in Spanish Fork, Utah.', 'Proclaiming the Gospel of Christ, Nurturing Faith, and Reaching out with the love of Christ.', 'grace-spanish-fork'),
('Grace (Moab)', 'Located in Moab, Utah.', 'To exist as a community of faith and confession in which we are personally and corporately embraced by the love of Jesus Christ, who empowers us through His Word and Sacraments to embrace one another in a fellowship of worship, caring, learning, serving, and reaching out.', 'grace-moab'),
('Holy Trinity (Logan)', 'Located in Logan, Utah.', 'To equip followers of Jesus to be powerful witnesses of the Gospel through their everyday lives.', 'holy-trinity-logan'),
('St. Paul', 'Located in Ogden, Utah.', 'To respond to the Great Commission by Proclaiming the Gospel of Jesus Christ; Bringing children and families into the Christian faith and fellowship of the Church; Nurturing the Christian faith in the families of the Church; and Providing a quality of Christian education.', 'st-paul'),
('Christ', 'Located in Murray, Utah.', 'God''s love in Jesus Christ empowers us to grow spiritually as we worship, serve, nurture & celebrate the fellowship within our church family, while proclaiming God''s unconditional love to our community.', 'christ-murray'),
('Holy Trinity (Riverton)', 'A mission plant of Grace Sandy, located in Riverton, Utah.', 'Committed to the spreading of the Gospel, good news, of our Savior Jesus Christ who was crucified and rose again for our salvation.', 'holy-trinity-riverton'),
('Trinity', 'Located in St. George, Utah.', 'Seeks ways to share the Gospel of Jesus Christ, His death and resurrection, with the people in Washington County, throughout the state of Utah, and around the world.', 'trinity-st-george'),
('Good Shepherd', 'Located in Richfield, Utah.', 'Experiencing the Love of God through Christ by: Seeking God''s will through His Word; Sharing our Lord''s love and forgiveness; and Serving and praising our Lord in prayer.', 'good-shepherd'),
('First', 'Located in Tooele, Utah. Focuses on historic Christian orthodoxy and the historical liturgy.', 'Sharing the Gospel.', 'first-tooele');
